import asyncio
import argparse
import nats
import numpy as np

async def main():

    parser = argparse.ArgumentParser()
    parser.add_argument('-t', '--type',
                        choices=['mockup', 'real'],
                        default='mockup',
                        help="Specifies weather the sensor values are randomly generated or come from a real sensor")

    parser.add_argument('-i', '--interval',
                        type=float,
                        default=2.0,
                        help="Time elapsed between sensor data packages sent")

    parser.add_argument('-r', '--range',
                        type=int,
                        nargs=2,
                        default=[0, 50],
                        help=""
                             "Minimun and maximum values that can be generated by the mockup sensor")

    args = parser.parse_args()
    sensor_type = args.type
    interval = args.interval
    data_range = args.range

    print("Starting application  with following configuration:")
    print(f"sensor_type: {sensor_type}")
    print(f"interval: {interval}")
    print(f"sensor_range: {data_range}")


    async def message_handler(msg):
        data = msg.data.decode()

        nonlocal send
        if data == "STOP":
            send = False
        if data == "RESUME":
            send = True


    nats_conection = await nats.connect('nats://localhost:4222')
    sensor_control_sub = await nats_conection.subscribe("ir_sensor.control", cb=message_handler)
    rng = np.random.default_rng()

    send = True

    while True:

        if send and sensor_type == "mockup":
            data_package = rng.integers(low=data_range[0], high=data_range[1], size=(64), dtype=np.int16)
            data_string = np.array2string(data_package)
            await nats_conection.publish('ir_sensor.data', data_string.encode('UTF-8'))

        elif send and sensor_type == "real":
            pass

        await asyncio.sleep(interval)

if __name__ == '__main__':
    asyncio.run(main())